### ISSUE TITLE
Authentication access denied

### ISSUE THREAD

**Issue by mrwrite** [NateRickard/Xamarin.Cognitive.BingSpeech#10]
My authentication is failing due to the fact that the endpoint of the library is different from the one I have for my azure key. How can override the current value before I authenticate?

**Comment by NateRickard** [comment]
I'll have to provide a way to override that.  What's the format of your endpoint?

**Comment by mrwrite** [comment]
@NateRickard 

My authentication endpoint is:
https://westus.api.cognitive.microsoft.com/sts/v1.0

My speech to text endpoint is:
https://westus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1
--




--

**Comment by NateRickard** [comment]
When I created a new Speech service in Azure I still received the same endpoints as before, but clearly this can vary...

I've updated the client with the following changes:

- Non-token authentication via the STT endpoint - https://docs.microsoft.com/en-us/azure/cognitive-services/speech/how-to/how-to-authentication?tabs=CSharp#use-a-subscription-key
  -  Need to set AuthenticationMode to `SubscriptionKey` to use this mode, and the auth endpoint is not used in this case
- Setting the auth endpoint to something different
  -  This will still use token auth, i.e. hit the auth endpoint to get the token, which lasts for 10 mins (this was the existing behavior)

Example:

```c#
speechClient.SpeechEndpoint = new Endpoint ("westus.stt.speech.microsoft.com", "/speech/recognition");
speechClient.AuthEndpoint = new Endpoint ("westus.api.cognitive.microsoft.com", "/sts/v1.0/issueToken");
```
