### ISSUE TITLE
Null detailedResult 

### ISSUE THREAD

**Issue by nexxuno** [NateRickard/Xamarin.Cognitive.BingSpeech#11]
Hello,
speecherecognition was working wonders in my app then all of a sudden it stopped working some days ago for no apparent reason. There is no error just a null return in detailed result:     

               var audioRecordTask = await recorder.StartRecording();

                    using (var stream = recorder.GetAudioFileStream())
                    {
                        //this will begin sending the recording audio data as it continues to record
                        var detailedResult = await bingSpeechClient.SpeechToTextDetailed(stream, recorder.AudioStreamDetails.SampleRate, audioRecordTask);
                        return detailedResult.Results != null && detailedResult.Results.Count > 0 ?
                            detailedResult.Results[0].ITN : string.Empty;
                    }

Am I the only one facing this problem?

Android 8.0 on a S7Edge

Thanks,
 Paolo

**Comment by nexxuno** [comment]
It looks like this overload solved the problem, this doesn't explain the root issue. Moreover having an exception of some kind would have helped.

                        var detailedResult = await bingSpeechClient.SpeechToTextDetailed(stream, recorder.AudioStreamDetails.SampleRate, recorder.AudioStreamDetails.ChannelCount,
                            recorder.AudioStreamDetails.BitsPerSample, audioRecordTask);

**Comment by nexxuno** [comment]
Disregard my last reply. I mean: using that overload returns a detailed result but there is no result in the array.

What's even more interesting is that my Azure service receives only the token calls but then there is no other call (I expected a server error or the like on the subsequent call).

If you can't reproduce this I can try and debug it when I have more time, please let me know, thanks.

**Comment by NateRickard** [comment]
Thanks for reporting.  I was able to reproduce this, and seems I just flipped some method params and it was causing it to send the wrong values to the service.  Also, exceptions will now be surfaced to the caller, although in this case the service was returning something extremely unhelpful.

Re: the other issue you discussed above... I'm able to get detailed results successfully using the sample app.  If you can reproduce this after [updating to 2.1.2](https://www.nuget.org/packages/Xamarin.Cognitive.BingSpeech/2.1.2) feel free to debug and send a PR or send me the repro.

**Comment by nexxuno** [comment]
Thanks I'll try this asap.
________________________________

**Comment by nexxuno** [comment]
@NateRickard  I still have problems:
SendRequest: Non-success status received :: Status Code: ServiceUnavailable; Reason: Service Unavailable; Content: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img { border:0 none; }#content { margin-left: auto; margin-right: auto }#logo { margin-top: 30px; width=120px; height=34px }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Bing</title></head><body><div id='content'><div id='logo'><img alt='Bing' src='data:image/gif;base64,R0lGODlheAAiAMQAAL/a9ECR3n+16e/2/BB11jCI28/j95/I7mCj5K/R8d/t+XCt5iB+2f+mFI++7FCa4f/u0/+sI/+xMZvF7v/YmP/04v/dpwBs0////wAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAB4ACIAAAX/ICCMAmaeaKqekNQ0kbXOdG3feI4JV3/ptMhrCAEaj8gcz5dECYeNYnNKNS571dYrQql6v7XrT6UAmAG5itQ2OAMUScPZkFI4HoEeYBIIOBwTXmInCQgFPogMDw5wSHZ5iD4BAnQ2BguHkRcFCwmQiGgCAAUFaFViAwIEmqwXCJUom3mmJwCfrZIHM7a4vRdoBwYjsFNiqz4ECA5nBwsMkQsDsT60Aw+RDMpmzZmSjScIkQWiAAkC3ay0YDusDLq7twXSJqAmA+gB6ii8yLDh3itGIUKwboWYHgjm1TiASB49aiY+EUhwA8CxTSbEEKzxrwfFgigObsTB0MeDh3ow/xioh2OljwQDLha4MeBZDwYgQyYysgARnHpXZur4hAAAonc2HCAiVlAM0hwKEJWo1zEAkCt+WNowCjEnOx/fdHSzWu+TVR1YuXrEobRrTlRHxmIoK+mqpAGITt6weYGAVxNqL3zUgdfHgrkQzdrtYbWnj6crOl4o8RfDxbM62qaky3jxBav3EEVbYa1h5YxHdRi4jPIXBsVo62IIjWzBGwwKCl288EBhZXSQZ6zu1xoNbCWyM+7GRSD4X9o9HoRNkQoRAVicP3vGbM8Bula9T6MonfcArdwIdhcglp37Daw0ypFI4Mk609P8fN0Mnn0kDvhAHHARAb6Jp5IzzCEwWIAKffRBxwINOkfDAQ0eZkQCAxlIGgAHkLDMdBoiIVmBIZYIUkkpmagiSBi6teKLVTjWA4gwwsgXgZawVuOOhDRE4gkGoHMfjy+i2JcABaaym4RErpjAcgEsIIAh2OjT5I5K+sIAkld2aU8CEPLFwCQA/OglkQMMoIABbCqQpokhAAA7'/></div><div id='message'><h2>Bing services aren't available right now</h2><p>We're working to restore all services as soon as possible.<br/>We know you want to get back to searching. Please check back soon.</p></div><div id='errorref'><span>Ref A: C081AD708A9A432AA438E2517B9EC0BE Ref B: MIL30EDGE0217 Ref C: 2018-09-24T14:13:58Z</span></div></div></body></html>

I'll try and debug what's going on ...

**Comment by NateRickard** [comment]
Assume this is Android... change your Android project to [use the Android HttpClient/Handler](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows).  This now seems to be required to successfully make calls to the speech api and I need to update the readme to reflect that.
