### ISSUE TITLE
Unable to find package NuGet.Build.Packaging with Version > 0.2.5-dev.1

### ISSUE THREAD

**Issue by githubuser212** [NateRickard/Xamarin.Cognitive.BingSpeech#18]
I struggling to build the IoS solution with the follow error:
Unable to find package NuGet.Build.Packaging with Version > 0.2.5-dev.1
Please advise. Thank you.

**Comment by NateRickard** [comment]
That package is only needed/used to build the NuGet package.  You can find some details on setting this up [here](https://github.com/naterickard/Plugin.AudioRecorder#building), otherwise you can just remove those references.
