### ISSUE TITLE
Little error in SpeechToTextDetailed()

### ISSUE THREAD

**Issue by lakadev** [NateRickard/Xamarin.Cognitive.BingSpeech#2]
Hello,

Thanks for your cool library.
For your information, there is little mistake in the main class BingSpeechApiClient in the method 
   `Task<RecognitionResult> SpeechToTextDetailed (string audioFilePath) `

The OutputMode used there is **Simple instead of Detailed** in line
   `() => CreateRequest (OutputMode.Simple),`
That causes the RecognitionResult to be Ok, but... always empty 

Thanks again.

**Comment by NateRickard** [comment]
@lakadev Thanks for reporting!  Copy/paste error :(  Fixed in 1.0.3.
