### ISSUE TITLE
Partial results

### ISSUE THREAD

**Issue by flocbit** [NateRickard/Xamarin.Cognitive.BingSpeech#5]
Hi there,

I was wondering if it's possible to receive partial results like on Bing Speech API website?
Could not find anything neither in docs nor in sample app.

Cheers

**Comment by flocbit** [comment]
I guess the only way to realise intermediate results is binding the client libraries...

**Comment by NateRickard** [comment]
I believe it requires using a websocket connection, which this lib does not do yet.
