### ISSUE TITLE
shows visualisation error while running the project

### ISSUE THREAD

**Issue by pritam004** [NateRickard/Xamarin.Cognitive.BingSpeech#7]
assembly `Xamarin.Cognitive.BingSpeech` is not loaded(NInterpretException)

**Comment by NateRickard** [comment]
This seems unrelated to this library, but maybe more to do with the Xamarin Live player based on the Google results I'm seeing.  Live Player may not be compatible with this library - I'm not sure and I do not use it.

You may want to try the latest version (v2.0.0) I just released as it's based on .NET Standard and may yield different results.

**Comment by pritam004** [comment]
thanks it works
