### ISSUE TITLE
InitialSilenceTimeout 

### ISSUE THREAD

**Issue by barun511** [NateRickard/Xamarin.Cognitive.BingSpeech#8]
Hey - this may not be an issue with the Bing Speech sdk, but I figured I'd report it anyway - I followed the instructions in the readme for the conversion of an audio file, but I keep getting an initial silence timeout. Is there a formatting custom that I don't know about? (I'm using mp3, xamarin 4.10 with VS 2017 on Oreo)

There's also a minor typo in the Readme - "hwoever this is not recommended" => "however this is not recommended" in the audio stream area.

**Comment by barun511** [comment]
Figured it out - I didn't read the instructions properly, I was using an Mpeg4 file!

On another note, is there a way to change the format that the speech SDK accepts, or does it have to be wav?

**Comment by NateRickard** [comment]
The last I checked in the API docs, it was required to be a WAV file.
